BIST100_SYMBOLS = [
    "AGHOL", "AGROT", "AKBNK", "AKFGY", "AKFYE", "AKSA", "AKSEN", "ALARK", "ALFAS", "AEFES", 
    "ARCLK", "ARDYZ", "ASELS", "ASTOR", "BTCIM", "BERA", "BIMAS", "BRSAN", "BRYAT", "BFREN", 
    "CCOLA", "CWENE", "CANTE", "CIMSA", "DOHOL", "DOAS", "ECZYT", "EGEEN", "ECILC", "EKGYO", 
    "ENJSA", "ENERY", "ENKAI", "EREGL", "EUREN", "EUPWR", "FROTO", "GESAN", "GOLTS", "GUBRF", 
    "SAHOL", "HEKTS", "ISGYO", "ISMEN", "IZENR", "KLSER", "KRDMD", "KTLEV", "KAYSE", "KCAER", 
    "KCHOL", "KONTR", "KONYA", "KOZAL", "KOZAA", "LMKDC", "MAVI", "MIATK", "MGROS", "OBAMS", 
    "ODAS", "OTKAR", "OYAKC", "PGSUS", "PEKGY", "PETKM", "QUAGR", "REEDR", "SASA", "SDTTR", 
    "SMRTG", "SKBNK", "SOKM", "TABGD", "TAVHL", "TKFEN", "TKNSA", "TOASO", "TUKAS", "TCELL", 
    "TMSN", "TUPRS", "THYAO", "TTKOM", "TTRAK", "GARAN", "HALKB", "ISCTR", "TSKB", "TURSG", 
    "SISE", "VAKBN", "ULKER", "VESBE", "VESTL", "YKBNK", "YYLGD", "YEOTK", "ZOREN", "BINHO"
]
